--USE EenmaalAndermaal
USE iproject48
/*
INSERT SCRIPT
*/

--==========================================================
INSERT INTO Vraag
VALUES (
		1, 
		'Wanneer is je moeder geboren?'
),
(		2,
		'Wat is de naam van je eerste huisdier?'
),
(		3,
		'Wat was je bijnaam op de middelbare school?'
),
(		4,
		'Wat is je favoriete maaltijd?'
),
(		5,
		'Bij welk bedrijf kreeg je je eerste baan?'
)
GO

--==========================================================
INSERT INTO Gebruiker
VALUES ( 
		 'MalleMan',
		 'Jan',
		 'Jansen',
		 'Groenewoud 11',
		 NULL,
		 '5043AG',
		 'Nijmegen',
		 'NLD',
		 '8 August 1990',
		 'MalleMan@hotmail.com',
		 'testwachtwoord',
		  1,
		 '4 February 1960',
		  1,
		  1,
		  NULL,
		  0
),
(		
		 'ZwoeleMan',
		 'Mark',
		 'Wahlberg',
		 'Tweekamp 11',
		 NULL,
		 '2012PF',
		 'Arnhem',
		 'NLD',
		 '22 January 1985',
		 'ZwoeleMan@hotmail.com',
		 'testwachtwoord',
		  2,
		 'Rufus',
		 0,
		 1,
		 NULL,
		 0
),
(		 
		 'Zuckerborg',
		 'Mark',
		 'Zuckerberg',
		 'Acaciastraat 10',
		 NULL,
		 '1204 TQ',
		 'Wijchen',
		 'NLD',
		 '6 May 1983',
		 'W4TCH1NGY0U@Botmail.com',
		 'TestWachtwoord',
		  5,
		 'Facebook',
		 1,
		 1,
		 NULL,
		 0
),
(		 
		 'HAXOR',
		 'Max',
		 'Smit',
		 'Oebranilaan 12',
		  NULL,
		 '9043 TY',
		 'Rotterdam',
		 'NLD',
		 '29 November 1994',
		 'Pegasister@gmail.com',
		 'TestWachtwoord',
		  2,
		 'Rex',
		 1,
		 1,
		 NULL,
		 0

),
(		 
		 'Piertje12',
		 'Roos',
		 'Malenboom',
		 'Veluwelaan 265',
		  NULL,
		 '5053CE',
		 'Otterlo',
		 'NLD',
		 '11 March 2001',
		 'Piertje12@gmail.com',
		 'TestWachtwoord',
		 4,
		 'Pannekoeken',
		 0,
		 1,
		 NULL,
		 0
)



GO
--===============================================
INSERT INTO Gebruikerstelefoon
VALUES ( 
		1,
		1,
		310653424234
		 
)

GO
--===============================================
INSERT INTO Rubriek
VALUES (
		1,
		'Speelgoed',
		1,
		1
)
GO
--===============================================
INSERT INTO Verkoper
VALUES (
		1,
		'Rabobank',
		'1234567',
		'Reader',
		'AB123CD456EF789'
),
(
		4,
		'Rabobank',
		'694946',
		'Reader',
		'B345E410G500'
),
(		3,
		'ABN Ambro',
		'6924234',
		'Reader',
		'OP869CYKA5032'

)


GO
--================================================
INSERT INTO Voorwerp
VALUES ( 
		'Lego-set',
		'Een oude lego-set.',
		25.00,
		'Online',
		NULL,
		'Nijmegen',
		'NLD',
		2,
		'23 april 2018',
		'22:00:00',
		NULL,
		NULL,
		1,
		NULL,
		'24 April 2018',
		'12:00:00',
		1,
		26.50
),

( 
		'Katana',
		'Een tweedehands Katana.',
		250.00,
		'Online',
		NULL,
		'Rotterdam',
		'NLD',
		16,
		'8 April 2018',
		'14:30:00',
		NULL,
		NULL,
		4,
		NULL,
		'8 May 2018',
		'09:00:00',
		0,
		NULL
),
( 
		'GTX 970',
		'Een tweedehands GPU.',
		200.00,
		'Online',
		NULL,
		'Rotterdam',
		'NLD',
		1,
		'22 April 2018',
		'16:45:00',
		NULL,
		NULL,
		4,
		3,
		'23 May 2018',
		'09:00:00',
		1,
		190.00
),
( 
		'Chipset',
		'Een tweedehands Chipset.',
		75.00,
		'Online',
		NULL,
		'Wijchen',
		'NLD',
		23,
		'31 March 2018',
		'02:00:00',
		NULL,
		NULL,
		3,
		1,
		'24 May 2018',
		'11:20:00',
		1,
		75.00
)
--===========================================
INSERT INTO Voorwerp_in_Rubriek
VALUES (
		1,
		1
)
GO
--===========================================
INSERT INTO Bestand
VALUES (
		'AB12',
		1
)
GO
--===========================================

INSERT INTO Bod
VALUES (
		1,
		26.50,
		2,
		'24 April 2018',
		'9:30:00'
),
(
		3,
		190.00,
		3,
		'23 April 2018',
		'8:30:00'
),
(		4,
		75.00,
		1,
		'21 April 2018',
		'20:00:00'
)
GO
--============================================
INSERT INTO Feedback
VALUES (
		1,
		'Gebruiker',
		'Positief',
		'24 April 2018',
		'16:30:00',
		'Dit is mijn commentaar!'
),
(
		3,
		'Gebruiker',
		'Positief',
		'24 April 2018',
		'15:30:00',
		'Prima!'
)

INSERT INTO Landen
VALUES  ('Canada', 'CAN'),
		('Frankrijk', 'FRA'),
		('Zwitserland', 'CHE'),
		('Malawi', 'MWI'),
		('Cuba', 'CUB'),
		('Suriname', 'SUR'),
		('Tunesië', 'TUN'),
		('Oostenrijk', 'AUT'),
		('België', 'BEL'),
		('Botswana', 'BWA'),
		('Iran', 'IRN'),
		('Nieuw-Zeeland', 'NZL'),
		('Zuid-Afrika', 'ZAF'),
		('Denemarken', 'DNK'),
		('Hongarije', 'HUN'),
		('Saoedi-Arabië', 'SAU'),
		('Liberia', 'LBR'),
		('Ethiopië', 'ETH'),
		('Chili', 'CHL'),
		('Marokko', 'MAR'),
		('Togo', 'TGO'),
		('Ghana', 'GHA'),
		('Laos', 'LAO'),
		('Angola', 'AGO'),
		('Filipijnen', 'PHL'),
		('Zambia', 'ZMB'),
		('Mali', 'MLI'),
		('Ivoorkust', 'CIV'),
		('Burma', 'BUR'),
		('Monaco', 'MCO'),
		('Colombia', 'COL'),
		('Albanië', 'ALB'),
		('Kameroen', 'CMR'),
		('Singapore', 'SGP'),
		('Paraguay', 'PRY'), 
		('Zweden', 'SWE'),
		('Cyprus', 'CYP'),
		('Papua New Guinea', 'PNG'),
		('Brunei', 'BRU'),
		('Irak', 'IRQ'),
		('Mauritius', 'MUS'),
		('Myanmar', 'MMR'),
		('Jemen', 'YEM'),
		('Slovenië', 'SLO'),
		('Kroatië', 'HRV'),
		('Taiwan', 'TWN'),
		('Rusland', 'RUS'),
		('Armenië', 'ARM'),
		('Ascension', 'SHN'),
		('Bahrein', 'BHR'),
		('Bhutan', 'BTN'),
		('Britse Antillen', 'IOT'),
		('Comoren', 'COM'),
		('Falkland-Eilanden', 'FLK'),
		('Frans Guyana', 'GUF'),
		('Gilbert- en Ellice-eilanden', 'GEL'),
		('Groenland', 'GRL'),
		('Guadeloupe', 'GLP'),
		('Macau', 'MAC'),
		('Martinique', 'MTQ'),
		('Mozambique', 'MOZ'),
		('Pitcairn-Eilanden', 'PCN'),
		('Guinee Bissau', 'GNB'),
		('Réunion', 'REU'),
		('Saint Pierre en Miquelon', 'SPM'),
		('Seychellen en Amiranten', 'SYC'),
		('Tonga', 'TON'),
		('Wallis en Futuna', 'WLF'),
		('Frans Polynesie', 'PYF'),
		('Johnston', 'JTN'),
		('Mayotte', 'MYT'),
		('Sikkim', 'SKM'),
		('Sint Vincent en de Grenadinen', 'VCT'),
		('Aruba', 'ABW'),
		('Burkina Faso', 'BFA'),
		('Azerbajdsjan', 'AZE'),
		('Wit-Rusland', 'BLR'),
		('Kazachstan', 'KAZ'),
		('Macedonië', 'MKD'),
		('Timor Leste', 'TLS'),
		('Servië', 'SRB'),
		('Montenegro', 'MNE'),
		('Moldavië', 'MDA'),
		('Burundi', 'BDI'),
		('Finland', 'FIN'),
		('Griekenland', 'GRC'),
		('Guatemala', 'GTM'),
		('Nigeria', 'NGA'),
		('Libië', 'LBY'),
		('Ierland', 'IRL'),
		('Brazilië', 'BRA'),
		('Rwanda', 'RWA'),
		('Venezuela', 'VEN'),
		('IJsland', 'ISL'),
		('Liechtenstein', 'LIE'),
		('Somalia', 'SOM'),
		('Verenigde Staten', 'USA'),
		('Bolivia', 'BOL'),
		('Australië', 'AUS'),
		('Jamaica', 'JAM'),
		('Luxemburg', 'LUX'),
		('Tsjaad', 'TCD'),
		('Mauritanië', 'MRT'),
		('Kyrgyzstan', 'KGZ'),
		('China', 'CHN'),
		('Afghanistan', 'AFG'),
		('Indonesië', 'IDN'),
		('Guyana', 'GUY'),
		('Vietnam', 'VNM'),
		('Noorwegen', 'NOR'),
		('San Marino', 'SMR'),
		('Duitsland', 'DEU'),
		('Nederland', 'NLD'),
		('Kambodja', 'KHM'),
		('Fiji', 'FJI'),
		('Bahama-eilanden', 'BHS'),
		('Israël', 'ISR'),
		('Nepal', 'NPL'),
		('Zuid-Korea', 'KOR'),
		('Spanje', 'ESP'),
		('Oekraine', 'UKR'),
		('Groot-Brittannië', 'GBN'),
		('Niger', 'NER'), 
		('Haïti', 'HTI'),
		('Jordanië', 'JOR'),
		('Turkije', 'TUR'),
		('Trinidad en Tobago', 'TTO'),
		('Bovenvolta', 'HVO'),
		('Algerije', 'DZA'),
		('Gabon', 'GAB'),
		('Noord-Korea', 'PRK'),
		('Oezbekistan', 'UZB'),
		('Sierra Leone', 'SLE'),
		('Honduras', 'HND'),
		('Frans Polynesië', 'PYF'),
		('Gibraltar', 'GIB'),
		('Timor-Leste', 'TLS'),
		('Tadzjikistan', 'TJK'),
		('Salomons-eilanden', 'SLB'),
		('São Tomé en Principe', 'STP'),
		('Sint Helena', 'SHN'),
		('Samoa', 'WSM'),
		('Toerkmenistan', 'TKM'),
		('Georgië', 'GEO'),
		('Bosnië-Herzegovina', 'BIH'),
		('Tsjechië', 'CZE'),
		('Slowakije', 'SVK'),
		('Democratische Republiek Congo', 'RCB'),
		('Uganda', 'UGA'),
		('Kenya', 'EAK'),
		('Malta', 'MLT'),
		('Barbados', 'BDS'),
		('Andorra', 'AND'),
		('Mexico', 'MEX'),
		('Costa Rica', 'CRI'),
		('Gambia', 'GMB'),
		('Syrië', 'SYR'),
		('Nederlandse Antillen', 'ANT'),
		('Egypte', 'EGY'),
		('Argentinië', 'ARG'),
		('Lesotho', 'LSO'),
		('Honduras', 'HND'),
		('Nicaragua', 'NIC'),
		('Pakistan', 'PAK'),
		('Senegal', 'SEN'),
		('Dahomey', 'DHY'),
		('Bulgarije', 'BGR'),
		('Maleisië', 'MYS'),
		('Dominicaanse Republiek', 'DOM'),
		('Polen', 'POL'),
		('Britse Maagdeneilanden', 'VGB'),
		('Tanzania', 'TZA'),
		('Rusland', 'RUS'),
		('El Salvador', 'SLV'),
		('Sri Lanka', 'LKA'),
		('Soedan', 'SDN'),
		('Japan', 'JPN'),
		('Hongkong', 'HKG'),
		('Panama', 'PAN'),
		('Uruguay', 'URY'),
		('Ecuador', 'ECU'),
		('Guinee', 'GIN'),
		('Maldiven', 'MDV'),
		('Thailand', 'THA'),
		('Libanon', 'LBN'),
		('Italië', 'ITA'),
		('Koeweit', 'KWT'),
		('India', 'IND'),
		('Roemenië', 'ROU'),
		('Peru', 'PER'),
		('Portugal', 'PRT'),
		('Oman', 'OMN'),
		('Mongolië', 'MNG'),
		('Verenigde Arabische Emiraten', 'ARE'),
		('Nauru', 'NRU'),
		('Palestina', 'PSE'),
		('Letland', 'LVA'),
		('Estland', 'EST'),
		('Litouwen', 'LTU'),
		('Bangladesh', 'BGD'),
		('Amerikaanse Maagdeneilanden', 'VIR'),
		('Caymaneilanden', 'CYM'),
		('Turkseilanden', 'TCA'),
		('Cookeilanden', 'COK'),
		('Tokelau-eilanden', 'TKL'),
		('Nieuw-Caledonië', 'NCL'),
		('Guam', 'GUM'),
		('Midway', 'MID'),
		('Wake', 'WAK'),
		('Pacific eilanden', 'PCI'),
		('Grenada', 'GRD'),
		('Marianen', 'MNP'),
		('Canton en Enderbury', 'CTE'),
		('Christmaseiland', 'CXR'),
		('Cocoseilanden', 'CCK'),
		('Faeröer', 'FRO'),
		('Montserrat', 'MSR'),
		('Norfolk', 'NFK'),
		('Belize', 'BLZ'),
		('Caicoseilanden', 'TCA'),
		('Puerto Rico', 'PRI'),
		('Papua-Nieuwguinea', 'PNG'),
		('Solomoneilanden', 'SLB'),
		('Benin', 'BEN'),
		('Kaapverdië', 'CPV'),
		('Seychellen', 'SYC'),
		('Kiribati', 'KIR'),
		('Tuvalu', 'TUV'),
		('Sint Lucia', 'LCA'),
		('Dominica', 'DMA'),
		('Zimbabwe', 'ZWE'),
		('Man', 'IMN'),
		('Anguilla', 'AIA'),
		('Saint Kitts-Nevis', 'KNA'),
		('Antigua', 'ATG'),
		('Sint Vincent', 'VCT'),
		('Gilberteilanden', 'GEL'),
		('Antigua en Barbuda', 'ATG'),
		('Eritrea', 'ERI'),
		('Kongo', 'RCB'),
		('Madagaskar', 'MDG'),
		('Namibië', 'NAM'),
		('Swaziland', 'SWZ'),
		('Katar', 'QAT'),
		('Aden', 'ADN'),
		('Zanzibar', 'EAZ'),
		('Marshalleilanden', 'MHL'),
		('Vanuatu', 'VUT'),
		('Westelijke Sahara', 'ESH'),
		('Micronesia', ''),
		('Svalbardeilanden', 'FSM'),
		('Bonaire', 'BES'),
		('Curaçao', 'CUW'),
		('Sint Maarten', 'SXM'),
		('Zuid-Soedan', 'SSD')

